apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops
  namespace: production
  labels:
    app: hello-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-devops
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: hello-devops
          image: ghcr.io/wamitinewton/hello-devops:3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15